name: review

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0
      
      - name: Run unit tests
        run: devbox run test
