name: review

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v4

      - name: Get Go version from go.mod
        id: get-go-version
        run: |
          version_go=$(grep '^go ' go.mod | awk '{print $2}')
          echo "version_go=$version_go" >> "$GITHUB_ENV"
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: $version_go
   
      - name: Install taskfile
        run: |
          sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
          task --version

      - name: Run unit tests
        run: task test
